# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Load all .zsh files from the Zsh config directory
export ZSH_CONFIG_DIR="$HOME/.zsh"
if [ -d "$ZSH_CONFIG_DIR" ]; then
  for config_file in "$ZSH_CONFIG_DIR"/*.zsh; do
    source "$config_file"
  done
  unset config_file
fi
unset ZSH_CONFIG_DIR

# Load Powerlevel10k configuration if it exists
# This is generated by `p10k configure`
if [[ -f ~/.p10k.zsh ]]; then
  source ~/.p10k.zsh
fi
