HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt HIST_IGNORE_DUPS HIST_IGNORE_SPACE HIST_VERIFY SHARE_HISTORY EXTENDED_HISTORY

# --- Navigation & Globbing ---
setopt AUTO_CD PUSHD_IGNORE_DUPS EXTENDED_GLOB

# --- Completion ---
setopt AUTO_MENU COMPLETE_IN_WORD

# --- Other ---
setopt NO_BEEP