#!/bin/zsh

function source_if_exists() {
  if [[ -r "$1" ]]; then
    source "$1"
  fi
}

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source_if_exists "$HOME/.p10k.zsh"
# source_if_exists "$HOME/.brewconfig.zsh"
source_if_exists "$HOME/.zsh/10-options.zsh"
source_if_exists "$HOME/.zsh/20-oh-my.zsh"
source_if_exists "$HOME/.zsh/30-alias.zsh"
source_if_exists "$HOME/.zsh/40-interactive.zsh"


# --- 42 School Specific ---
if [[ "$HOST" == *"42london"* ]]; then
#   source_if_exists "$HOME/.zsh/42-school.zsh"
fi
